// Generated by https://quicktype.io

export interface MediaGallery {
	_key: string;
	_type: string;
	features: null;
	defaultTag: null;
	searchTags: null;
	description: string;
	title: string;
	gallery: Gallery[];
}

export interface Gallery {
	title: string;
	image: Image;
	_type: string;
	description: string;
	_key: string;
}

export interface Image {
	alt: string;
	asset: Asset;
	_type: string;
}

export interface Asset {
	_type: string;
	_ref: string;
}
