// Generated by https://quicktype.io

export interface Reviews {
	_key: string;
	_type: string;
	features: null;
	heading: string;
	tagline: string;
	testimonials: Testimonial[];
	title: string;
}

export interface Testimonial {
	_key: string;
	_type: string;
	author: string;
	body: string;
	rating: number;
	title: string;
}
